# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import model_pb2 as model__pb2


class VideoStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamFrames = channel.stream_stream(
                '/video_streaming.VideoStream/StreamFrames',
                request_serializer=model__pb2.VideoFrame.SerializeToString,
                response_deserializer=model__pb2.Model_Data.FromString,
                )


class VideoStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamFrames(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamFrames': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamFrames,
                    request_deserializer=model__pb2.VideoFrame.FromString,
                    response_serializer=model__pb2.Model_Data.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'video_streaming.VideoStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VideoStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamFrames(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/video_streaming.VideoStream/StreamFrames',
            model__pb2.VideoFrame.SerializeToString,
            model__pb2.Model_Data.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
